### ISSUE TITLE
The player can phase through the bottom of baseplates and plates if they jet underneath them

### ISSUE THREAD

**Issue by Lucbeebo** [ClayHanson/BlocklandRebuilt-IssueBoard#131]
### Bug Description
Plates starting with 4x4f and above can all be phased through in this way. This specific clip doesn't happen in retail.

### Screenshots
![BLRebuilt_O7j5s3iKzh](https://github.com/ClayHanson/Blockland-Rebuilt-BetaTesters/assets/130931873/4c4895c7-0e3b-4a2f-952b-05485f3521dd)
All green plates can be phased through, red ones cannot.

### Metadata:
 - Game Version: `v0.18`

**Comment by Kenkoman** [comment]
I cant seem to reproduce this anymore in `v2.6`, this is probably resolved?
