### ISSUE TITLE
Tank turret controls are strange with angles

### ISSUE THREAD

**Issue by Cowtastic141** [ClayHanson/BlocklandRebuilt-IssueBoard#154]
Tank turret controls don't properly behave when looking past the minimum / maximum height for the barrel

![tank](https://github.com/ClayHanson/Blockland-Rebuilt-BetaTesters/assets/119779017/955ccbb0-8915-4714-a995-74c9b5718cfa)

 - Game Version: `v0.19`
 
This doesn't happen on retail

**Comment by Kenkoman** [comment]
This issue is included in #101, closing as duplicate
