### ISSUE TITLE
Can't stand up while inside another player's world box

### ISSUE THREAD

**Issue by Zinlock** [ClayHanson/BlocklandRebuilt-IssueBoard#172]
### Bug Description
Crouching while inside another player's world box prevents you from standing up despite it not matching their collision box

### Screenshots

https://github.com/ClayHanson/Blockland-Rebuilt-BetaTesters/assets/33813303/e0a4d3ae-4bfd-4621-8857-412f04dd17f5

### Metadata:
 - Game Version: `v0.21`

**Comment by Kenkoman** [comment]
Was fixed at some point, closing
