### ISSUE TITLE
Bricks that change color or fx cause nearby bricks to blink

### ISSUE THREAD

**Issue by Zinlock** [ClayHanson/BlocklandRebuilt-IssueBoard#248]
### Bug Description
When a brick changes colors or fx, it blinks along with any other brick it covers

### Screenshots

https://github.com/ClayHanson/Blockland-Rebuilt-BetaTesters/assets/33813303/0604e8fd-b92a-4f78-bbc8-786a91755fcf

### Metadata:
 - Game Version: `v0.33`

**Comment by Kenkoman** [comment]
It appears this was fixed at some point, closing
