### ISSUE TITLE
Players can't collide with objects created within their bounds

### ISSUE THREAD

**Issue by Zinlock** [ClayHanson/BlocklandRebuilt-IssueBoard#271]
### Bug Description
If an object is created within a player's bounds, they will not be able to collide with it until they move away.

### Screenshots
(demonstrated with bricks, but this also seems to happens with other object types like triggers)

https://github.com/ClayHanson/Blockland-Rebuilt-BetaTesters/assets/33813303/0ca1b8f4-e55a-4a66-8e1e-d580004d4a30

### Metadata:
 - Game Version: `v0.41`

**Comment by Kenkoman** [comment]
This was fixed at some point, closing
