### ISSUE TITLE
Demo restrictions should be relaxed to what they are in V21

### ISSUE THREAD

**Issue by ClayHanson** [ClayHanson/BlocklandRebuilt-IssueBoard#283]
### Bug Description
In Blockland v21, the only thing you cannot do in Demo Mode is connect to online games. You can load add-ons, play singleplayer, have no brick limit, etc. It would be nice if Rebuilt had this behavior.

### Metadata:
 - Game Version: `v1.0`

**Comment by Kenkoman** [comment]
This was implemented a while ago, closing
