### ISSUE TITLE
Vehicle third person driver camera breaks when a turret is mounted

### ISSUE THREAD

**Issue by Zinlock** [ClayHanson/BlocklandRebuilt-IssueBoard#300]
### Bug Description
When a vehicle has a turret mounted to it (like the default Tank), it locks the driver's third person camera in place.

### To Reproduce
1. Spawn a Tank
2. Get in the driver seat
3. Third person camera is stuck in place, not even free look can unlock it

### Metadata:
 - Game Version: `v1.0`

**Comment by Kenkoman** [comment]
This issue appears to also be happening on [Vehicle_Aseed](https://blocklandglass.com/addons/addon/1355) and [Vehicle_Amarok](https://blocklandglass.com/addons/addon/965) too, despite those cars not having any mounted turrets.
