### ISSUE TITLE
Hate emote is incorrect

### ISSUE THREAD

**Issue by siliconOpossum** [ClayHanson/BlocklandRebuilt-IssueBoard#304]
### Description
should be dark smoke, instead it's light smoke

### To Reproduce
type /hate, see incorrect color

### Screenshots
Rebuilt:
![image](https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/assets/138069572/132701b9-0cdb-4c43-a6b8-5aac4e024bf5)
V20:
![image](https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/assets/138069572/f3b3115a-8318-4e91-a60f-f7a03d9cf1a1)

### Metadata:
 - Game Version: `v1.0`

**Comment by maxymax13** [comment]
https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/issues/290?

**Comment by ClayHanson** [comment]
Duplicate of https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/issues/290 .
