### ISSUE TITLE
Auto admin doesn't work

### ISSUE THREAD

**Issue by Cowtastic141** [ClayHanson/BlocklandRebuilt-IssueBoard#305]
### Bug Description
Joining your own server registers that you should have super admin but does not properly apply it.
You cannot open the administrator menu or use `/dwand`.

### To Reproduce
1. Start a dedicated server
2. Join it
3. Try and open admin menu

### Metadata:
 - Game Version: `v1.1`

**Comment by ClayHanson** [comment]
I cannot replicate this issue, other than `/dwand` not working -- It's not `/dwand`, it's `/magicwand`.

**Comment by consoleSkunk** [comment]
This *was* an issue in one of the QA builds (secure client cmds weren't sent) but was quickly fixed before release.
