### ISSUE TITLE
setJumpForce

### ISSUE THREAD

**Issue by ConanODoyle** [ClayHanson/BlocklandRebuilt-IssueBoard#307]
### Feature Pitch
See title.

### Potential Use Cases
Could make people jump high idk.

### How will it work?
Same way as `setMaxForwardSpeed()` and the rest of the gang does. Will require some networking changes probably?

### Additional info
will let me host an enhanced "don't jump" server

**Comment by ClayHanson** [comment]
Added in the form of these three methods:
`Player::setJumpForce` - Sets the jump force. This will override the datablock's jumpForce value.
`Player::getJumpForce` - Allows you to get the current jump force value. If a custom value is not set, it'll return the datablock's value.
`Player::resetJumpForce` - Clears the custom jump force value and reverts back to using the datablock's jumpForce value.
