### ISSUE TITLE
No sent message history

### ISSUE THREAD

**Issue by Monoblaster** [ClayHanson/BlocklandRebuilt-IssueBoard#315]
### Description
In v21 you can press up and down while in the send message prompt to select up to the 8 previously sent messages.

### To Reproduce
1. Send a message
2. Enter the message prompt again
3. Press up to select your previous message
4. Nothing happens

### Metadata:
 - Game Version: `v1.1`

**Comment by consoleSkunk** [comment]
Works for me - do you by chance have the game thinking either shift or ctrl is held down?

Edit: Also make sure "Press Up to Repeat Chat" is enabled in advanced options.

**Comment by Monoblaster** [comment]
I had it disabled I guess. Is it not enabled by default or did it get disabled when I transferred my pref files.

**Comment by consoleSkunk** [comment]
It should be enabled by default, actually
