### ISSUE TITLE
Expose net flag 8

### ISSUE THREAD

**Issue by Monoblaster** [ClayHanson/BlocklandRebuilt-IssueBoard#327]
### Description
I was using net flag 8 in my 2d billboards script to freeze player objects for mounting lights to. Without this or another solution I don't think this is possible to have an easy place to attach lights to without them being affected by gravity. This is inconsistent with v21's selective ghosting dll as the only other useful net flag.

### To Reproduce
1. Try to use net flag 8
2. Notice that it's not exposed

### Screenshots
If applicable, add screenshots or video to help show the inconsistency. Direct comparison images between retail and rebuilt is appreciated.

### Metadata:
 - Game Version: `v1.2`

### Additional context
The script I am referencing:
https://github.com/Monoblaster/Support_BillboardsV2

**Comment by ClayHanson** [comment]
I added some new methods to address this:

`NetObject::setIsGhostable`
`NetObject::getIsGhostable`
