### ISSUE TITLE
onBallHit -> Bounce event broken

### ISSUE THREAD

**Issue by maxymax13** [ClayHanson/BlocklandRebuilt-IssueBoard#331]
### Bug Description
the bounce/redirect event for balls seems to trigger the onballhit event again when it bounces, causing the ball to start jittering in place as it repeatedly gets bounced and reset back in place. doing this for a lot of balls at once will cause lag from all the projectiles being deleted and remade

### To Reproduce
1. event brick with onBallHit -> bounce with any parameter
2. throw ball at it
3. ball will repeteadly bounce in place
4. spawn a ton of more balls on the brick to start lagging the server

### Metadata:
 - Game Version: `v1.2`

**Comment by Kenkoman** [comment]
this can only be reproduced with certain angles but can still be reproduced in `v2.6`
