### ISSUE TITLE
It is extremely easy to clip through ceilings by jetting

### ISSUE THREAD

**Issue by Kenkoman** [ClayHanson/BlocklandRebuilt-IssueBoard#337]
### Description
Just by jetting into a ceiling, it is extremely easy to clip through said ceiling. This could be a big problem for maps where the player is not intended to go out of bounds or access certain areas.

### Screenshots
Rebuilt:
https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/assets/25954813/7f9d2051-5c19-430e-89bd-4f609559094d

Retail:
https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/assets/25954813/b8a4753b-e0e0-4973-84f6-b2b14220d837

### Metadata:
 - Game Version: `v1.2`

### Additional context
It appears the player bouncing off the ceiling in retail may greatly reduce the potential for clipping through

**Comment by ClayHanson** [comment]
Duplicate of #131?

**Comment by consoleSkunk** [comment]
The aformentioned issue only mentions bricks, however it's also possible on interior objects:

https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/assets/50500602/c0906617-393a-4b84-ba03-f8a4eb500c11

**Comment by Kenkoman** [comment]
Duplicate of #131
