### ISSUE TITLE
TriggerData::onTickTrigger only ticks on the most recently encountered object in the trigger

### ISSUE THREAD

**Issue by Pecon** [ClayHanson/BlocklandRebuilt-IssueBoard#343]
### Bug Description
If two or more applicable objects enter a trigger together, only the one that entered most recently will get called on by onTickTrigger

### To Reproduce
Create a trigger with an onTickTrigger callback and have two players enter simultaneously.

Here is some sloppy reproduction debug code that makes a trigger in the Bedroom.
```
datablock TriggerData(debugTriggerData){tickPeriodMS = 200;};
function debugTriggerData::onTickTrigger(%this,%trigger,%player){%player.client.centerPrint("hi",1);}
new Trigger(){position = %position;datablock = debugTriggerData;polyhedron = "0.0 0.0 0.0 1.0 0.0 0.0 0.0 -1.0 0.0 0.0 0.0 1.0";position="68 -72 287";};
```

### Screenshots
![image](https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/assets/7043178/04184538-0705-401b-980c-42ed02d0a111)
![image](https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/assets/7043178/3567b853-d9bc-4348-80c3-3e0c6cabd822)

### Metadata:
 - Game Version: `v1.2`

### Additional context
Discovered in Boss Battles due to Slayer capture points not working as intended with multiple players on the same capture point.

**Comment by Kenkoman** [comment]
This was fixed in `v2.2`
