### ISSUE TITLE
DLSS/Frame Interpolation for slight performace boost

### ISSUE THREAD

**Issue by stixc** [ClayHanson/BlocklandRebuilt-IssueBoard#355]
### Feature Pitch
For Blockland Rebuilt, I'd wish for some form of DLSS or some kind of frame interpolation to be implemented into the game, as a way to remedy poor performance on a lot of builds, even on higher end systems.

### How will it work?
Within the options menu is a way to enable DLSS, and possibly a drop-down menu to switch between different presets (Balanced, Performance, etc). With it enabled, it uses GPU power, AI, etc to interpolate frames within the game when it senses frame drops. So something that is apox. 16 FPS or so can easily go back to 60 FPS, even if it looks a tiny bit sloppy. Obviously it can be a tiny bit better with the draw distance set to low/automatic, and vice versa, but would be nice considering the game's performance, even on modern systems, is still not that great, especially with builds that are above 100k bricks, tons of particles, effects, etc.

### Additional info
I expect instead for Blockland Rebuilt to have major performance updates to remove the laggy jank Torque has, but if it's not possible, then hopefully implementing frame interpolation could be a good solution.

**Comment by maxymax13** [comment]
question: how would you go about adding interpolation to an ancient engine using openGL 1.X and (nonfunctional) DX5? does NVIDIA have public resources for developers to add this to their games?

anyways, a simple slider for 3D resolution scale like in UE4 games would be a really nice feature to have, even if it's not possible to do fancy upscaling to it

**Comment by ClayHanson** [comment]
There is no "resolution scale" in OpenGL that won't negatively impact performance, and DLSS is not supported by OpenGL.
