### ISSUE TITLE
String table capitalization is applied to UI elements modified by scripts

### ISSUE THREAD

**Issue by consoleSkunk** [ClayHanson/BlocklandRebuilt-IssueBoard#358]
### Bug Description
UI elements modified by scripts can occasionally have incorrect capitalization.

### Screenshots
![Screenshot_2023-07-26_15-31-09](https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/assets/50500602/94f12c89-640f-4005-abf4-7cacfef7075b)
![Screenshot_2023-07-26_15-34-58](https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/assets/50500602/32386258-4139-4870-a88e-ecff185ade04)

### Metadata:
 - Game Version: `v1.3`

**Comment by Elletra** [comment]
Yeah this is an issue with Torque. [Button text is inserted into the string table case insensitively.](https://github.com/Electrk/tge14/blob/master/%24HWNDPARENT/engine/gui/controls/guiButtonBaseCtrl.cc#L90)

**Comment by ClayHanson** [comment]
You are awesome Electrk, thanks for pointing me straight to the problem code

**Comment by consoleSkunk** [comment]
This is fixed in v1.4.
