### ISSUE TITLE
Map_Anapolictic freezes clients when spawning in

### ISSUE THREAD

**Issue by Kenkoman** [ClayHanson/BlocklandRebuilt-IssueBoard#362]
### Bug Description
The map [Anapolictic](https://bl.kenko.dev/Add-ons/Retail/Map/Map_Anapolictic.zip) hangs clients on spawn. A server can load the map fine, but any client trying to spawn into it will have their games freeze just before they spawn.

### Metadata:
 - Game Version: `v1.4-rev1880`

**Comment by ClayHanson** [comment]
I cannot replicate this issue

**Comment by Kenkoman** [comment]
On a completely clean (other than this map) install of `v1.5-rev1904` I can still replicate this

**Comment by ClayHanson** [comment]
This seems to be an issue with release build optimizations. I have addressed the issue.

**Comment by consoleSkunk** [comment]
Confirmed fixed in `v1.9`
