### ISSUE TITLE
Make `GameConnection::setBlackOut()` work for all clients

### ISSUE THREAD

**Issue by Elletra** [ClayHanson/BlocklandRebuilt-IssueBoard#364]
### Feature Pitch
Right now, `GameConnection::setBlackOut()` only works on localConnections (i.e. `ServerConnection`). I think it would be cool to have it usable on servers on all clients.

**Comment by Elletra** [comment]
Better yet, why not make a `GameConnection::fadeScreen(bool fadeIn, int timeMS, ColorI color)` that lets us fade to whatever color we want?

Maybe also `GameConnection::onFadeOut()` and `GameConnection::onFadeIn()` callbacks?

**Comment by Trogtor** [comment]
lol i didnt even see this before i made my suggestion

**Comment by ClayHanson** [comment]
Both GameConnection and ShapeBase can now be flashed with the following function:
`setScreenFlash(<duration in MS>, <ColorF start color>, <ColorF end color>)`
