### ISSUE TITLE
client > setColorFlash function

### ISSUE THREAD

**Issue by Trogtor** [ClayHanson/BlocklandRebuilt-IssueBoard#365]
### Feature Pitch
Function that works like the setWhiteOut & setDamageFlash does but you can use any color.

### Potential Use Cases
Many different colors could be used for different effects to add cinematic effect or visual queues in certain minigames
- Black color fading out at the start of a minigame (For suspense)
- New items that grant buffs or debuffs that are color coded by the on screen effect

### Additional info
This function could have more variables that are not possible with setWhiteOut & setDamageFlash such as
- Overall intensity of the color
- How long the color stays before it fades out
- Length in milliseconds of the fadeout

Perhaps even an additional _**fade in**_ where instead the color fades in indefinitely (or until the color-staying variable runs out which will then flash back to normal)

Also, making this a client variable instead of a player variable would allow the possibility for spectators to see the effect

**Comment by Elletra** [comment]
https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/issues/364#issuecomment-1657048315

**Comment by ClayHanson** [comment]
Can be implemented in #364 -- Closing
