### ISSUE TITLE
member fields on server playertypes editable clientside

### ISSUE THREAD

**Issue by maxymax13** [ClayHanson/BlocklandRebuilt-IssueBoard#368]
### To Reproduce
1. join a server where you are forced to be in first person
2. `serverconnection.getControlObject().getdatablock().firstPersonOnly = 0; `
3. unfair advantage obtained

### Metadata:
 - Game Version: `v1.4`

**Comment by consoleSkunk** [comment]
![Screenshot_2023-07-31_09-56-14](https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/assets/50500602/1169949f-6dce-468a-bd0f-50ae243c8031)

This works in v21 as well.
