### ISSUE TITLE
GetNodeColor

### ISSUE THREAD

**Issue by ConanODoyle** [ClayHanson/BlocklandRebuilt-IssueBoard#376]
### Feature Pitch
%shapebase.getNodeColor(%nodeName);

### Potential Use Cases
Not have to rely on specific client fields or packaging over setNodeColor to capture colors for later reference

### How will it work?
Anything to do with player node colors like swapping visible nodes while retaining current color, or bot weapons that simulate hands

### Additional info
No(de).

**Comment by ClayHanson** [comment]
Does the current implementation not work?

**Comment by ConanODoyle** [comment]
Wasn't sure if there was one and ran into this while coding for retail blockland - close this I guess lol

**Comment by ghost** [comment]
> Wasn't sure if there was one and ran into this while coding for retail blockland - close this I guess lol

Nevermind what I said, looks like it is getNodeColor after all.
