### ISSUE TITLE
Modern Blockland car mods have broken cameras (and vanilla tank)

### ISSUE THREAD

**Issue by mrwallace888** [ClayHanson/BlocklandRebuilt-IssueBoard#387]
### Bug Description

The third person camera for modern-day car mods from Blockland Retail (think Filipe1020's cars and other stuff) is broken, and I'm not sure as to what the cause of it is. Console doesn't show anything.

The camera in first person is fine, but in third person, the camera is locked to the rear of the car (though you can still move your Blockhead's head around), and it gets jittery when you drive and steer. Same thing with the vanilla tank, and you can even see the turret on it spazzing out when driving in first person.

### Screenshots

https://streamable.com/01fmtd

### Metadata:
 - Game Version: `v2.1`

**Comment by Kenkoman** [comment]
Replacing this issue with #300 and #391
