### ISSUE TITLE
Ghost brick disappears when moved.

### ISSUE THREAD

**Issue by Dglider** [ClayHanson/BlocklandRebuilt-IssueBoard#390]
### Bug Description
The ghost brick disappears every time I move it.  When tested on a flat map like slate, it appears to be teleporting to 0,0,0.

### To Reproduce
Install BL Rebuilt.
Place a ghost brick.
Move the ghost brick.

### Metadata:
 - Game Version: v2.3
 - OS: Windows 7 (64x)

### Additional context
I tested this on a fresh install and the bug is still present.

**Comment by Kenkoman** [comment]
I've tested this on `v2.2` and this bug isn't present, which indicates this bug was introduced in the latest `v2.3` update.

**Comment by ClayHanson** [comment]
Fixed in https://github.com/ClayHanson/Blockland-Rebuilt/commit/731630560cb89fdbfbc151b80745cbc046571d6c .
