### ISSUE TITLE
Audio Description inconsistency causing CTD

### ISSUE THREAD

**Issue by mrwallace888** [ClayHanson/BlocklandRebuilt-IssueBoard#394]
### Bug Description
I've been adding engine sounds to a few vehicle mods of mine, and noticed a very strange inconsistency. The audio profile used for a looping engine sound is AudioEngineLooping3D. For some of my cars, it works fine, for others, it's crashing to desktop as soon as the engine sound gets called and starts playing.

![image](https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/assets/39398330/31d6545e-dc34-446a-a709-b1012e836e87)
This is one of the vehicles I edited, Filipe's Club. With each vehicle I'm adding a "Shared_Data_Audio.cs" file to addon which defines the engine sounds, and then gets executed by the vehicle's server.cs file. This vehicle works perfectly fine. So far it also works for the CityVan and Euro.

![image](https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/assets/39398330/d81fdfd9-443f-45e8-ba75-e7f0acedec22)
Now here's the same file from another addon, the Roadster. All I did was rename the .wavs and the name of the profile, just like I normally do with my stuff. This works for the other cars, but this car crashes to desktop. Keep in mind, when I get in the car, the engine startup sound still plays and the game still runs. But after the startup sound finishes, it starts playing the loop, and once the loop is called, that's when the game crashes.

![image](https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/assets/39398330/b2d0057c-26e2-45ad-b0c4-1bd1b576eb35)
Unlike the Club and other cars, this error appears in the console for the Roadster. This might be why the game CTDs. However, I don't understand why this is the case.

This seems inconsistent, you can clearly see the contents of Shared_Data_Audio.cs for the Roadster is exactly the same as the Club, yet for the Roadster, it says that "AudioEngineLooping3D" is not a member of the class all of a sudden. Even though nothing has changed and nothing is different.

Crashlog had some stuff too, not sure if it's relevant.
![image](https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/assets/39398330/6f886efc-03a9-459e-856e-cef5f6278d24)
![image](https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/assets/39398330/fe842e7d-6e3a-4b01-a33f-46e20efff264)

Here's the full crash log, the dmp, and the console log.
[crash_14H_20M_57S_04-22-2024.log](https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/files/15067989/crash_14H_20M_57S_04-22-2024.log)
[crash_14H_20M_57S_04-22-2024.dmp](https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/files/15067995/crash_14H_20M_57S_04-22-2024.dmp)
[console.log](https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/files/15067996/console.log)

### Metadata:
 - Game Version: `v2.7`

Noticed something odd, too. It doesn't seem like AudioEngineLooping3D is a real description but that's what Support_EngineSounds seems to officially use, and it still wouldn't explain why it still sometimes works for a select few cars. I never even had this CTD issue on Retail either.

**Comment by mrwallace888** [comment]
Just in case, I tried taking one of the cars that was CTDing and changed the Shared_Data_Audio thing so instead of AudioEngineLooping3D, it was AudioDefaultLoop3D, an official audio description, and I still got "Object 'AudioDefaultLoop3d' is not a member of the 'AudioDescription' data block class" in the console.

**Comment by Pecon** [comment]
You should verify that the 'AudioEngineLooping3D' AudioDescription datablock is defined in your add-on code, as it may be that you're relying on another add-on's definition of it.

Also, for reference, the base game code defines `AudioDefaultLooping3d`, `AudioCloseLooping3d`, and `AudioClosestLooping3d` as the three main default 3d looping audio descriptions. `AudioDefaultLoop3d` is not provided by anything. https://github.com/Elletra/bl-decompiled/blob/000d36339bb31fef446f6446e2c1bc795f39824d/server/scripts/allGameScripts.cs#L7428

**Comment by mrwallace888** [comment]
I'm not sure where Support_EngineSounds gets "AudioEngineLooping3D" from, but I'm still just trying to figure out why this still works for some cars and not for others when nothing else has been changed. It doesn't seem like I'm missing anything from the other cars that work.

I'll send you some of my files if you'd like to take a look for yourself.
[Vehicle_Club2.zip](https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/files/15068499/Vehicle_Club2.zip)
[Vehicle_Euro2.zip](https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/files/15068500/Vehicle_Euro2.zip)
[Vehicle_Roadster2.zip](https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/files/15068501/Vehicle_Roadster2.zip)
[Vehicle_CityVan2.zip](https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/files/15068503/Vehicle_CityVan2.zip)
[Vehicle_Zenoz2.zip](https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/files/15068509/Vehicle_Zenoz2.zip)
[Support_EngineSounds.zip](https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/files/15068513/Support_EngineSounds.zip)

Euro, Club, and CityVan work fine. Roadster and Zenoz CTD and have that console error.

**Comment by Pecon** [comment]
Reviewing your console.log, the issue here is that your AudioProfiles are being defined before the AudioDescription you want (`AudioEngineLooping3d`) is loaded. The issue is plainly obvious when you review where Support_EngineSounds, which contains the definition, is finally loaded in the console.log relative to your vehicles. Note that the Add-On Vehicle_Hydric is correctly forcing the load of Support_EngineSounds, which then allows it and subsequently loading add-ons to use that audio description.

When utilizing an external resource like this, you need to add a similar loader in your add-on's code which loads the dependency before you go and use it; otherwise you end up with the problem you have here where you inconsistently may or may not have the datablock defined depending on load order and whether that add-on was enabled at all.
